name: Will Lewis
email: will@wflewis.com
baseurl: ""
url: ""
github_username:  willamin
title: "Will Lewis"

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink: pretty
