[build]
  base    = ""
  publish = "build"
  command = "make build"

[[redirects]]
  from = "/resume.pdf"
  to = "/resume_1808.pdf"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "sameorigin"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'self'"

[[headers]]
  for = "/"
  [headers.values]
    Link = "</stylesheets/main.css>; rel=preload; as=style"
